@extends('layouts.master')
    @section('content')
    <title> User Terms </title>
        <link rel="stylesheet" href="{{ asset('assets/CSS/User Terms.CSS')}}"/>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

<P id="wel">Welcome to Skakr, the ultimate fashion destination for trendsetters like yourself! At Skakr, <span style="display: block;"></span> we're all about embracing your unique style and expressing yourself through fashion. Whether <span style="display: block;"></span> you're a fashion-forward individual or someone who loves to experiment with different looks, <span style="display: block;"></span> we've got you covered.</P>
        <p id="our">Our collection is carefully curated to cater to all your fashion needs. From chic and classic pieces to <span style="display: block;"></span> bold and edgy designs, we have something for everyone. We believe that fashion should be accessible <span style="display: block;"></span> and inclusive, which is why our sizes range from petite to plus, ensuring that every body type can find <span style="display: block;"></span> their perfect fit.</p>
        <p id="we">At Skakr, we understand that fashion is more than just clothes. It's an art form that allows you to <span style="display: block;"></span> showcase your personality and make a statement. That's why our team of talented designers works <span style="display: block;"></span> tirelessly to create pieces that are not only stylish but also of the highest quality. We source the finest <span style="display: block;"></span> fabrics and pay attention to every little detail, so you can feel confident and comfortable in our <span style="display: block;"></span> garments.</p>
        <p id="pride">We pride ourselves on providing exceptional customer service. Our friendly and knowledgeable staff <span style="display: block;"></span> is always ready to assist you and answer any questions you may have. We want your shopping <span style="display: block;"></span> experience to be enjoyable and hassle-free, so we offer fast shipping and hassle-free returns. </p>
        <p id="join">Join the Skakr community today and unleash your fashionista spirit! Be sure to follow us on social <span style="display: block;"></span> media for style inspiration, exclusive offers, and the latest fashion trends. Don't forget to tag us in your <span style="display: block;"></span> Skakr outfits—we love seeing how you rock our pieces!</p>
        <p id="fashion">At Skakr, fashion is a celebration of individuality, creativity, and self-expression. So go ahead, <span style="display: block;"></span> explore our collection, and let your style speak volumes. Welcome to the world of Skakr, where <span style="display: block;"></span> fashion dreams come to life!</p>
        
@endsection
